# Build on Ubuntu Trusty
dist: trusty

# Use new container infrastructure to enable caching
sudo: false

# Hawk uses Haskell
language: haskell

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.cabal

# Ensure necessary system libraries are present
addons:
  apt:
    # probably not neccessary
    #update: true
    sources:
      - sourceline: 'ppa:hvr/ghc' # PPA of Haskell packages
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main' 
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main'
    packages:
      - libgmp-dev           # required by cabal
      - cabal-install-2.0    # required by GHC 8.x
      - llvm-6.0-dev         

ghc:
  - "8.4"

# Keep git pulls small
git:
  depth: 5
  
  
install:
  # Build dependencies
  - cabal new-configure

script:
  # Build the package, its tests, and its docs and run the tests
  - cabal new-test language-hawk
